[ffmpeg]
root = "F:\\ffmpeg"
ffprobe = "F:\\ffmpeg\\bin\\ffprobe.exe"
ffmpeg = "F:\\ffmpeg\\bin\\ffmpeg.exe"

[system]
cpu_limit_percent = 90
ram_limit_percent = 80
disk_free_gb_min = 20
max_preview_workers = 1
max_final_workers = 1
auto_refresh_seconds = 10
