from __future__ import annotations


_STYLE_PRESETS: dict[str, dict[str, dict[str, object]]] = {
    "sale_blast": {
        "main": {
            "position": "top",
            "alignment": "center",
            "vertical_alignment": "middle",
            "textbox_alignment": "center",
            "textbox_mode": "grouped",
            "textbox_height_mode": "content_hug",
            "font_family": "TH Baijam",
            "font_fallbacks": ["TH Chakra Petch", "THSarabun", "Tahoma", "Arial Unicode MS"],
            "font_size": 96,
            "min_font_size": 48,
            "font_weight": "bold",
            "text_color": "#FFFFFF",
            "stroke_color": "#1A1A1A",
            "stroke_width": 4,
            "background_color": "#D61F3A",
            "background_opacity": 0.34,
            "box_border_color": "#FFD447",
            "box_border_opacity": 0.98,
            "box_border_width": 4,
            "padding": 28,
            "max_lines": 2,
            "preferred_line_count": 2,
            "max_chars_per_line": 16,
            "textbox_width_ratio": 0.78,
            "textbox_height_ratio": 0.18,
            "line_spacing_ratio": 0.10,
            "line_advance_ratio": 0.82,
            "safe_top_ratio": 0.14,
            "safe_bottom_ratio": 0.48,
            "overflow_policy": "wrap_then_scale_then_review",
            "enter_animation": "pop_in",
            "review_required_if_overflow": True,
        },
        "sub": {
            "position": "bottom",
            "alignment": "center",
            "vertical_alignment": "middle",
            "textbox_alignment": "center",
            "textbox_mode": "grouped",
            "textbox_height_mode": "content_hug",
            "font_family": "TH Baijam",
            "font_fallbacks": ["TH Chakra Petch", "THSarabun", "Tahoma", "Arial Unicode MS"],
            "font_size": 48,
            "min_font_size": 30,
            "font_weight": "bold",
            "text_color": "#FFFFFF",
            "stroke_color": "#111111",
            "stroke_width": 3,
            "background_color": "#111827",
            "background_opacity": 0.88,
            "box_border_color": "#F8FAFC",
            "box_border_opacity": 0.94,
            "box_border_width": 3,
            "padding": 18,
            "max_lines": 2,
            "preferred_line_count": 1,
            "max_chars_per_line": 22,
            "textbox_width_ratio": 0.52,
            "textbox_height_ratio": 0.11,
            "line_spacing_ratio": 0.10,
            "line_advance_ratio": 0.92,
            "safe_top_ratio": 0.58,
            "safe_bottom_ratio": 0.82,
            "overflow_policy": "wrap_then_scale_then_review",
            "enter_animation": "fade_in",
            "review_required_if_overflow": True,
        },
    },
    "clean_cta": {
        "main": {
            "position": "center",
            "alignment": "center",
            "vertical_alignment": "middle",
            "textbox_alignment": "center",
            "textbox_mode": "grouped",
            "textbox_height_mode": "content_hug",
            "font_family": "TH Baijam",
            "font_fallbacks": ["TH Chakra Petch", "THSarabun", "Tahoma", "Arial Unicode MS"],
            "font_size": 72,
            "min_font_size": 40,
            "font_weight": "bold",
            "text_color": "#FFFFFF",
            "stroke_color": "#0F172A",
            "stroke_width": 3,
            "background_color": "#0F172A",
            "background_opacity": 0.78,
            "box_border_color": "#CBD5E1",
            "box_border_opacity": 0.82,
            "box_border_width": 2,
            "padding": 22,
            "max_lines": 2,
            "preferred_line_count": 2,
            "max_chars_per_line": 22,
            "textbox_width_ratio": 0.68,
            "textbox_height_ratio": 0.16,
            "line_spacing_ratio": 0.12,
            "line_advance_ratio": 0.88,
            "safe_top_ratio": 0.18,
            "safe_bottom_ratio": 0.54,
            "overflow_policy": "wrap_then_scale_then_review",
            "enter_animation": "fade_in",
            "review_required_if_overflow": True,
        },
        "sub": {
            "position": "bottom",
            "alignment": "center",
            "vertical_alignment": "middle",
            "textbox_alignment": "center",
            "textbox_mode": "grouped",
            "textbox_height_mode": "content_hug",
            "font_family": "TH Baijam",
            "font_fallbacks": ["TH Chakra Petch", "THSarabun", "Tahoma", "Arial Unicode MS"],
            "font_size": 36,
            "min_font_size": 24,
            "font_weight": "medium",
            "text_color": "#F8FAFC",
            "stroke_color": "#0F172A",
            "stroke_width": 2,
            "background_color": "#1E293B",
            "background_opacity": 0.72,
            "box_border_color": "#94A3B8",
            "box_border_opacity": 0.78,
            "box_border_width": 2,
            "padding": 14,
            "max_lines": 2,
            "preferred_line_count": 1,
            "max_chars_per_line": 28,
            "textbox_width_ratio": 0.62,
            "textbox_height_ratio": 0.10,
            "line_spacing_ratio": 0.14,
            "line_advance_ratio": 0.94,
            "safe_top_ratio": 0.62,
            "safe_bottom_ratio": 0.86,
            "overflow_policy": "wrap_then_truncate_or_review",
            "enter_animation": "fade_in",
            "review_required_if_overflow": True,
        },
    },
    "benefit_stack": {
        "main": {
            "position": "center",
            "alignment": "left",
            "vertical_alignment": "middle",
            "textbox_alignment": "center",
            "textbox_mode": "per_line",
            "textbox_height_mode": "content_hug",
            "font_family": "TH Baijam",
            "font_fallbacks": ["TH Chakra Petch", "THSarabun", "Tahoma", "Arial Unicode MS"],
            "font_size": 72,
            "min_font_size": 40,
            "font_weight": "bold",
            "text_color": "#FFFFFF",
            "stroke_color": "#111827",
            "stroke_width": 3,
            "background_color": "#0F766E",
            "background_opacity": 0.86,
            "box_border_color": "#CCFBF1",
            "box_border_opacity": 0.92,
            "box_border_width": 3,
            "padding": 20,
            "max_lines": 4,
            "preferred_line_count": 3,
            "max_chars_per_line": 18,
            "textbox_width_ratio": 0.74,
            "textbox_height_ratio": 0.20,
            "line_spacing_ratio": 0.12,
            "line_advance_ratio": 1.0,
            "safe_top_ratio": 0.14,
            "safe_bottom_ratio": 0.50,
            "overflow_policy": "wrap_then_scale_then_review",
            "enter_animation": "pop_in",
            "review_required_if_overflow": True,
        },
        "sub": {
            "position": "bottom",
            "alignment": "left",
            "vertical_alignment": "middle",
            "textbox_alignment": "center",
            "textbox_mode": "grouped",
            "textbox_height_mode": "content_hug",
            "font_family": "TH Baijam",
            "font_fallbacks": ["TH Chakra Petch", "THSarabun", "Tahoma", "Arial Unicode MS"],
            "font_size": 34,
            "min_font_size": 22,
            "font_weight": "medium",
            "text_color": "#FFFFFF",
            "stroke_color": "#0F172A",
            "stroke_width": 2,
            "background_color": "#134E4A",
            "background_opacity": 0.82,
            "box_border_color": "#99F6E4",
            "box_border_opacity": 0.84,
            "box_border_width": 2,
            "padding": 16,
            "max_lines": 3,
            "preferred_line_count": 1,
            "max_chars_per_line": 28,
            "textbox_width_ratio": 0.70,
            "textbox_height_ratio": 0.12,
            "line_spacing_ratio": 0.14,
            "line_advance_ratio": 0.96,
            "safe_top_ratio": 0.62,
            "safe_bottom_ratio": 0.88,
            "overflow_policy": "wrap_then_truncate_or_review",
            "enter_animation": "fade_in",
            "review_required_if_overflow": True,
        },
    },
}


def caption_style_preset_names() -> tuple[str, ...]:
    return tuple(sorted(_STYLE_PRESETS))


def resolve_caption_style_preset(*, preset_name: str, role: str) -> dict[str, object]:
    normalized_preset = preset_name.strip().casefold()
    normalized_role = role.strip().casefold()
    preset = _STYLE_PRESETS.get(normalized_preset)
    if preset is None:
        raise ValueError(f"Unknown caption style preset: {preset_name}")
    role_defaults = preset.get(normalized_role)
    if role_defaults is None:
        raise ValueError(f"Caption style preset {preset_name} does not define role {role}.")
    return dict(role_defaults)
